---
apiVersion: v1
kind: Namespace
metadata:
  name: harbor
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: harbor
  namespace: kube-system
spec:
  chart: "harbor"
  repo: "https://helm.goharbor.io"
  targetNamespace: harbor
  valuesContent: |
      externalURL: https://harbor.lab.k7s.dev
      expose:
        # Set how to expose the service. Set the type as "ingress", "clusterIP", "nodePort" or "loadBalancer"
        # and fill the information in the corresponding section
        type: ingress
        tls:
          # Enable TLS or not.
          # Delete the "ssl-redirect" annotations in "expose.ingress.annotations" when TLS is disabled and "expose.type" is "ingress"
          # Note: if the "expose.type" is "ingress" and TLS is disabled,
          # the port must be included in the command when pulling/pushing images.
          # Refer to https://github.com/goharbor/harbor/issues/5291 for details.
          enabled: true
          # The source of the tls certificate. Set as "auto", "secret"
          # or "none" and fill the information in the corresponding section
          # 1) auto: generate the tls certificate automatically
          # 2) secret: read the tls certificate from the specified secret.
          # The tls certificate can be generated manually or by cert manager
          # 3) none: configure no tls certificate for the ingress. If the default
          # tls certificate is configured in the ingress controller, choose this option
          certSource: none
          auto:
            # The common name used to generate the certificate, it's necessary
            # when the type isn't "ingress"
            commonName: ""
          secret:
            # The name of secret which contains keys named:
            # "tls.crt" - the certificate
            # "tls.key" - the private key
            secretName: ""
            # The name of secret which contains keys named:
            # "tls.crt" - the certificate
            # "tls.key" - the private key
            # Only needed when the "expose.type" is "ingress".
            notarySecretName: ""
        ingress:
          hosts:
            core:  harbor.lab.k7s.dev
            notary: notary.lab.k7s.dev